version: '3.5'

services:

  training:
    image: ml-kurkkumopo-training
    volumes:
      - ./src/imgs:/src/imgs
      - ./src/model:/src/model

  backend:
    image: ml-kurkkumopo-backend
    volumes:
      - ./src/model:/src/model:ro
    ports:
      - 5000:5000
      
  frontend:
     image: ml-kurkkumopo-frontend
     ports:
       - 3000:3000
