FROM ubuntu:18.04

# Schematics in 1.14 suggest the container should listen on port 8000
EXPOSE 8000
ENV DEBIAN_FRONTEND=noninteractive
ENV PATH=$PATH:/usr/local/go/bin
ENV PORT 8000

WORKDIR /usr/src/app
RUN useradd -m appuser
RUN apt-get update -qq
RUN (apt-get -y install curl) > /dev/null 2>&1
RUN curl -sL https://dl.google.com/go/go1.16.6.linux-amd64.tar.gz | gzip -dc | ( cd /usr/local && tar xf - )

COPY . .
RUN go build

USER appuser

CMD ["./server"]
