FROM node:latest

EXPOSE 5000

ENV DEBIAN_FRONTEND=noninteractive
ENV REACT_APP_BACKEND_URL=http://localhost:8080

WORKDIR /usr/src/app
COPY . .

RUN useradd -m appuser && \
    npm install && \
    npm run build && \
    npm install -g serve

USER appuser

CMD ["serve", "-s", "-l", "5000", "build"]
