version: '3.5'

services:
  backend:
      image: example-backend
      environment:
      - REQUEST_ORIGIN=http://localhost:5000
      ports:
      - 8080:8000
      container_name: example-backend
  frontend:
      image: example-frontend
      ports:
      - 5000:5000
      container_name: example-frontend
