version: '3.5'

services:
  redis-cache:
      image: redis
  backend:
      image: example-backend
      environment:
      - REDIS_HOST=redis-cache
      ports:
      - 8080:8000
  frontend:
      image: example-frontend
      ports:
      - 5000:5000
