FROM alpine:latest as build-stage

WORKDIR /usr/src/app
COPY . .
ENV PORT 8000

RUN adduser --disabled-password appuser && \
    apk add --no-cache go && \
    CGO_ENABLED=0 go build

FROM scratch

ENV PORT 8000
EXPOSE 8000

WORKDIR /usr/src/app

COPY --from=build-stage /usr/src/app/server /usr/src/app/server
COPY --from=build-stage /etc/passwd /etc/passwd
COPY --from=build-stage /etc/group /etc/group

USER appuser

CMD ["./server"]
