version: '3.5'

services:

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=example
    container_name: db_redmine
    volumes:
      - database:/var/lib/postgresql/data

  redis-cache:
      image: redis

  backend:
      image: example-backend
      environment:
      - REDIS_HOST=redis-cache
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=example

  frontend:
      image: example-frontend

# NB nginx:alpine does not work and backend proxy_pass requires the backlash
  reverseproxy:
     image: nginx
     volumes:
     - ../part2.8/nginx.conf:/etc/nginx/nginx.conf:ro
     ports:
     - 80:80

volumes:
  database:
